### PR TITLE
Remove launch_path from manifest.webapp

### PR DESCRIPTION
**Pull request by tofumatt**
Close bug 1156550

### CODE REVIEW

**Comment by tofumatt** [comment]
Not needed in there for non-packaged apps either.

**Comment by fwenzel** [comment]
But _with_ it, this _can_ be turned into a packaged app, no?

**Comment by fwenzel** [comment]
I don't want to prohibit turning it into a packaged app, I just want to avoid forcing it to be.

Likewise, keep in mind this will be used inside WebIDE, which by default sends packaged apps to its simulators. Will that still work?

**Comment by tofumatt** [comment]
Packaged apps are on the way out though, so including this could be a point of confusion? If someone needs to make a packaged app they'll run into this line in the docs... _right_?

**Comment by fwenzel** [comment]
Sure, we'll land this when most FxOS devices rely on hosted apps, and when WebIDE makes hosted apps by default.

**Comment by tofumatt** [comment]
Either this can be merged in or... we should probably just close it :smile:

**Comment by fwenzel** [comment]
Since the currently deployed code doesn't have it, let's drop it

**Pull request closed without merging**
